# Generated by Django 5.0.6 on 2024-05-20 10:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transcribe',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.TextField(default='none')),
                ('trans_result', models.TextField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('profile_pic', models.TextField(default='https://pbs.twimg.com/media/GN_WWe5aUAAZk-S?format=jpg&name=4096x4096')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sentences',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sentence', models.TextField()),
                ('sa_score', models.FloatField(default=0)),
                ('sa_tag', models.CharField(choices=[('N', 'Negative'), ('O', 'Neutral'), ('P', 'Positive')], default='O', max_length=1)),
                ('id_trans', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sentence', to='analyticts.transcribe')),
            ],
        ),
        migrations.AddField(
            model_name='transcribe',
            name='user_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='transcribe', to='analyticts.user'),
        ),
    ]
