# Generated by Django 5.0.6 on 2024-05-30 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyticts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentence',
            name='sentiment',
            field=models.JSONField(default=list),
        ),
    ]
