# Generated by Django 5.0.6 on 2024-05-31 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyticts', '0002_sentence_sentiment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sentence',
            name='sentiment',
        ),
        migrations.AddField(
            model_name='sentence',
            name='negative',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='sentence',
            name='neutral',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='sentence',
            name='positive',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=5),
        ),
    ]
