# Generated by Django 5.0.6 on 2024-06-02 06:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyticts', '0003_remove_sentence_sentiment_sentence_negative_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Named',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('label', models.TextField()),
                ('transcription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analyticts.transcription')),
            ],
        ),
    ]
