# Generated by Django 5.0.6 on 2024-06-05 15:25

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyticts', '0004_named'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='transcription',
            name='created_by',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transcription',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transcription',
            name='file_name',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='named',
            name='label',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='named',
            name='text',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='sentence',
            name='text',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='transcription',
            name='text',
            field=models.TextField(default=''),
        ),
    ]
